### ISSUE TITLE
Keyboard and fullscreen not working.

### ISSUE THREAD

**Issue by NF3RN0** [ricrpi/mupen64plus#12]
Took me a little bit to get it compiled and start testing again. Fresh NOOBS Install from the non-dev branch. I did have to set APIDIR manually from the console when I compiled. Keyboard is not working, and it worked in previous builds, I have tried everything. The other thing I cannot get to work is the screen sized is windowed on the bottom left corner, tried everything I knew to force it to fullscreen. Everything else seems to work just fine or better than it did before.

**Comment by gizmo98** [comment]
The keyboard issue should be a SDL2 configuration problem. Keyboard runs fine with RetroPie-Setups build script and SDL2 package.

The force fullscreen problem is video plugin related. Vice and gles2n64 do only respect resolution settings of mupen64plus.cfg and gles2n64.cfg.
