### ISSUE TITLE
Mario Kart 64 - Black Screens On Multiplayer

### ISSUE THREAD

**Issue by whoot** [ricrpi/mupen64plus#18]
Hey,
thank you for this wonderful emulator!
But I have an issue with Mario Kart 64:
When playing Mario Kart 64 in multiplayer, only Player 1 is visible. All other players have a black screen.

Any suggestions?

Greetings

**Comment by ricrpi** [comment]
All I can suggest is you search on the Raspberry Pi forum (Assumming this is for the Pi or Pi2) or try changing the configuration for the video plugin you are using

**Comment by gizmo98** [comment]
Use rice plugin. Gles2n64 does not work with mk64 splitscreen.

**Comment by gizmo98** [comment]
The black screen issue should be fixed.

**Comment by jamesmacwhite** [comment]
Confirmed. Mario Kart 64 with the newer builds of mupen64plus using gles2n64 as video plugin no longer has the black screen issue on Multiplayer. Previously, you had switch to the rice plugin but it wasn't as smooth.

For RetroPi users, I just ran the retropi-setup.sh and installed binary version of mupen64plus, I also installed the experimental packages, but not a requirement.

**Comment by whoot** [comment]
Yes, double screen works now. 
But now the menu is fucked up.. images are distorted and you have to pick everything blind.
I know that this is a known issue. Gues you cant have both :/

**Comment by jamesmacwhite** [comment]
Interesting. At least on RetroPi, after installing a newer binary of mupen64plus, I don't get corruption in the menus. This always occurred on Libretro on Mario Kart 64.

Default video plugin glesn64 works well for me.

**Comment by gizmo98** [comment]
@whoot this problem should only occur if you use mupen64plus-libretro.

**Comment by whoot** [comment]
Hmm. How can i verify this?
I ran the retropi-setup.sh and updated the binarys. I also made "source code installation" for mupen64-plus.

**Comment by gizmo98** [comment]
We merged all different n64 rom folders. To select a default emulator for all games or for a specific rom press x/m after game selection/start. If you start a game there is a console message for a short time which indicates this. As long as the message shows up you can press x or m.
