### ISSUE TITLE
Problem when parsing defaultList

### ISSUE THREAD

**Issue by lhotamir** [ricrpi/mupen64plus#19]
Hello

I have a following problem

When I run the build.sh script it finishes with following error:

`error: The requested URL returned error: 403 while accessing https://github.com/VFP=1/mupen64plus-VFP=1/info/refs
fatal: HTTP request failed`

This is probably a problem with parsing of the defaultList file because VFP=1 is used as a flag for the mupen64plus-core component. For some reason the script is treating it as a separate component, which of course does not exist.

Thank you for your help

**Comment by ricrpi** [comment]
Fixed
