### ISSUE TITLE
build.sh bugs with SDL2 detection

### ISSUE THREAD

**Issue by joolswills** [ricrpi/mupen64plus#5]
In build.sh line 171 you have if checking for `/usr/local/lib/libSDL2.so`

if it finds it (true in my case as I have SDL2 locally installed), the script will then fail with the next pushd which does

"pushd ${BUILDDIR}/${SDL2}" which gets run even if SDL hasn't been downloaded.

**Comment by joolswills** [comment]
we include SDL2 as packaged debs on retropie now which install to /usr/bin - we don't really want another SDL2 installed in /usr/local/ - regarding the issue you had with it working from console if built with X - I've not seen this behaviour so I'll test, but I know that it is required to build without opengl (as you do currently), else if someone has raspbian sdl1 installed it will have pulled in opengl headers etc, and so SDL2 will try and build with opengl. 

Please could you add an option to your build script to skip the SDL2 stuff completely, so it will just use our pre-installed SDL2.

**Comment by joolswills** [comment]
sorry - I had a brain glitch during part of that your script doesn't actually install SDL2 right ? just builds it withint the build location and links with it ? - we previously had SDL2 installed in /usr/local/ and your script I believe checks for that, but we now use /usr since we are using a debian package of sdl2

**Comment by ricrpi** [comment]
I wasn't aware that SDL2 is now in the raspian package repository. I can see it in Jessie now, is it in wheezy too? 

I would rather use raspbian package to save people having the 1h compile time but I would like to test before changing the script.

**Comment by joolswills** [comment]
it's not - we build it from source - see https://github.com/petrockblog/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl2.sh

**Comment by ricrpi** [comment]
I have added to the script to check the users PATH for sdl2-config. Retro-Pie can disable the SDL stuff use CHECK_SDL2=0 ./build.sh but it should work  with checking.

The SDL2 package in Jessie doesn't have SDL_VIDEO_DRIVER_RPI enabled so is not very helpful at the moment.

**Comment by joolswills** [comment]
yeh - I'm hoping raspbian devs will fix up the sdl2 package in jessie for pi - as it would be nice to move away at some point from having to maintain/build it.

Many thanks for the script changes - I will give it a test. Cheers.
